CREATE DATABASE  IF NOT EXISTS `CRUD-Krew-Pepowiny`;
USE `CRUD-Krew-Pepowiny`;

--
-- Table structure for table `MOTHER`
--
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `HOSPITAL_ADRESS`;

CREATE TABLE `HOSPITAL_ADRESS` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `city` varchar(128) DEFAULT NULL,
  `zip_code` varchar(45) DEFAULT NULL,
  `prefix` varchar(45) DEFAULT NULL,
  `street` varchar(45) DEFAULT NULL,
  `house_number` varchar(45) DEFAULT NULL,
  `local_number` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `HOSPITAL`;

CREATE TABLE `HOSPITAL` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `hostpital_name` varchar(45) DEFAULT NULL,
  `hospital_adress_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_HOSPITAL_ADRESS_idx` (`HOSPITAL_ADRESS_id`),
  CONSTRAINT `FK_HOSPITAL_ADRESS` FOREIGN KEY (`HOSPITAL_ADRESS_id`) REFERENCES `HOSPITAL_ADRESS` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

SET FOREIGN_KEY_CHECKS = 1;