CREATE DATABASE  IF NOT EXISTS `CRUD-Krew-Pepowiny`;
USE `CRUD-Krew-Pepowiny`;

--
-- Table structure for table `UMBILICAL_CORD_BLOOD`

--
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `UMBILICAL_CORD_BLOOD_DETAIL`;

CREATE TABLE `UMBILICAL_CORD_BLOOD_DETAIL` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `donation_code` varchar(128) DEFAULT NULL,
  `donation_data` date,
  `donation_comments` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `UMBILICAL_CORD_BLOOD`;

CREATE TABLE `UMBILICAL_CORD_BLOOD` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `umbilical_cord_blood_detail_id` int(11) DEFAULT NULL,
  `mother_id` int(11) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_UMBILICAL_CORD_BLOOD_DETAIL_idx` (`UMBILICAL_CORD_BLOOD_DETAIL_id`),
  CONSTRAINT `FK_UMBILICAL_CORD_BLOOD_DETAIL` FOREIGN KEY (`UMBILICAL_CORD_BLOOD_DETAIL_id`) REFERENCES `UMBILICAL_CORD_BLOOD_DETAIL` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  KEY `FK_MOTHER_idx` (`MOTHER_id`),
  CONSTRAINT `FK_MOTHER` FOREIGN KEY (`MOTHER_id`) REFERENCES `MOTHER` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  KEY `FK_USER_idx` (`USER_id`),
  CONSTRAINT `FK_USER` FOREIGN KEY (`USER_id`) REFERENCES `USER` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

SET FOREIGN_KEY_CHECKS = 1;